name:                tshsh
version:             0.1.0.0
github:              "githubuser/tshsh"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2021 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/tshsh#readme>

dependencies:
- base >= 4.7 && < 5
- text
- bytestring
- unix
- protolude
- process
- safe-exceptions
- terminal-size
- attoparsec
- stm
- string-conversions
- containers

- shh
- shh-extras
- lens
- lens-regex-pcre
- pretty-simple
- lens-aeson
- raw-strings-qq
- ansi-terminal

- array
- random
- mtl
- hspec-expectations-lens
- profunctors
- gauge
- strip-ansi-escape
- bounded-tchan
- strict
- ListLike

default-extensions:
- StrictData
- BangPatterns
- DeriveAnyClass
- DeriveGeneric
- DerivingStrategies
- FlexibleContexts
- FlexibleInstances
- GeneralizedNewtypeDeriving
- LambdaCase
- MultiParamTypeClasses
- NoImplicitPrelude
- NoMonomorphismRestriction
- OverloadedStrings
- RecordWildCards
- ScopedTypeVariables
- StandaloneDeriving
- TypeSynonymInstances

library:
  source-dirs: src

executables:
  tshsh:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=--nonmoving-gc
    - -with-rtsopts=-N2
    - -O2
    - -Wall
    dependencies:
    - tshsh
  bench-exe:
    main:                Main.hs
    source-dirs:         bench
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O2
    - -Wall
    dependencies:
    - tshsh

tests:
  tshsh-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - tshsh
    - hspec
    - hspec-core
    - hspec-contrib
    - QuickCheck
    - HUnit
    - containers
