name:                tshsh
version:             0.0.0.0
github:              "kevroletin/tshsh"
license:             BSD3
author:              "Vasiliy Kevroletin"
maintainer:          "kevroletin@gmail.com"
copyright:           "2021 Vasiliy Kevroletin"

extra-source-files:
- README.md

synopsis:            A terminal multiplexer that allows switching between two interactive shells.
                     It doesn't render the tui interface but instead passes all the data from
                     shells to the "real" terminal. It parses shell output to determine the
                     boundaries between shell commands and uses it to synchronize some states
                     between shells.

category:            program, terminal

description:         Please see the README on GitHub at <https://github.com/kevroletin/tshsh#readme>

dependencies:
- base >= 4.7 && < 5
- ListLike
- ansi-terminal
- array
- bytestring
- containers
- directory
- gauge
- hspec-expectations-lens
- lens
- mtl
- optparse-applicative
- process
- protolude
- safe-exceptions
- stm
- strict
- string-conversions
- strip-ansi-escape
- terminal-size
- text
- unix

default-extensions:
- StrictData
- DataKinds
- BangPatterns
- DeriveAnyClass
- DeriveGeneric
- DerivingStrategies
- FlexibleContexts
- FlexibleInstances
- GeneralizedNewtypeDeriving
- LambdaCase
- MultiParamTypeClasses
- NoImplicitPrelude
- NoMonomorphismRestriction
- OverloadedStrings
- RecordWildCards
- ScopedTypeVariables
- StandaloneDeriving
- TypeSynonymInstances

library:
  source-dirs: src

executables:
  tshsh:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=--nonmoving-gc
    - -with-rtsopts=-N2
    - -O2
    - -Wall
    dependencies:
    - tshsh
  bench-exe:
    main:                Main.hs
    source-dirs:         bench
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O2
    - -Wall
    dependencies:
    - tshsh

tests:
  tshsh-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - tshsh
    - hspec
    - hspec-core
    - hspec-contrib
    - QuickCheck
    - HUnit
    - containers
